### ISSUE TITLE
about the implement of sort error

### ISSUE THREAD

**Issue by FL77N** [kemaloksuz/RankSortLoss#12]
according the paper, I can compute the  $L_{ij}$ as following defined in Eq. 9:
![微信截图_20211231155145](https://user-images.githubusercontent.com/56532204/147811723-98e19f88-bba5-4d58-8834-f8cb61fc9afd.png)
I notice that the implement of sort error in your code is as following:
```
# Compute sorting error on example ii
sorting_error[ii] = current_sorting_error - target_sorting_error
```
why not multiply the sort pmf? as following
```
sorting_error[ii] = (current_sorting_error - target_sorting_error)*missorted_examples/sorting_pmf_denom
```

**Comment by kemaloksuz** [comment]
Your expression seems correct. In terms of our implementation.
- We first compute the sorting error (\ell_S(i)- \ell_S^*(i) in Eq. 9 in the paper - https://arxiv.org/pdf/2107.11669.pdf) in line 66: https://github.com/kemaloksuz/RankSortLoss/blob/b41f64df70b1f8e3260e5c04015e0c7b59b339d9/mmdet/models/losses/ranking_losses.py#L66
-  Then, this sorting error is distributed over positive examples using sorting pmf in this line: https://github.com/kemaloksuz/RankSortLoss/blob/b41f64df70b1f8e3260e5c04015e0c7b59b339d9/mmdet/models/losses/ranking_losses.py#L87.  In otherwords, sorting pmf is taken into account in line 87.
Please feel free to ask further questions if you have.

**Comment by FL77N** [comment]
Thank you for the detailly reply! I notice that in the [RankSortLoss/mmdet/models/losses/ranking_losses.py Line 87 in b41f64d](https://github.com/kemaloksuz/RankSortLoss/blob/b41f64df70b1f8e3260e5c04015e0c7b59b339d9/mmdet/models/losses/ranking_losses.py#L87) sorting pmf is used to compute the gradient caused by the sort loss, however, (\ell_S(i)- \ell_S^*(i) should mutiply the sort pmf like the rank error. I clear that for the gradient of sort error is calculated correctly, the BP will be fine. Actually, Our final goal is the gradient.

**Comment by FL77N** [comment]
Sry! I got it! We will compute the integral of (current_sorting_error - target_sorting_error)*sorting_pmf for sorting_error[ii], then sorting_error[ii] should equal  (current_sorting_error - target_sorting_error) as same as in the paper.
