### ISSUE TITLE
How to apply RankSort Loss on SOLO model?

### ISSUE THREAD

**Issue by usherbob** [kemaloksuz/RankSortLoss#5]
Hi Kemal,

Thanks for sharing your code. I tried to implement RS Loss for SOLO mode through descriptions in your paper, i.e. 

> use Dice Loss as the continuous ground truth labels. 

However, I found that since mask branch and category branch are disentangled in SOLO model, there is no one-one correspondence in mask predictions and category predictions. Therefore, I cannot figure out how to regress category predictions with their corresponding mask dice loss.

Best regards,
Jiahua Wang

**Comment by kemaloksuz** [comment]
Hi Jiahua,

Thanks for your interest. Please check out our provisional release for Rank & Sort Loss on SOLOv2 (unfortunately it is based on mmdetection v1, and hence not compatible with this repo currently), and then feel free to get in touch again in case of questions. 

The link to SOLOv2 implementation: https://github.com/kemaloksuz/RankSortLoss-Solov2

Kemal
